# Database
spring.datasource.url=${DEV_DATASOURCE_URL}
spring.datasource.username=${DEV_DATASOURCE_USERNAME}
spring.datasource.password=${DEV_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# JPA
spring.jpa.hibernate.ddl-auto=update

# Gmail Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${DEV_MAIL_USERNAME}
spring.mail.password=${DEV_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

mail.default.cc=${DEV_MAIL_DEFAULT_CC}
mail.from=${DEV_MAIL_FROM}


# Connection Pool
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

