spring.application.name=virtu-stock
spring.config.import=optional:file:.env[.properties]

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# IPO Alerts
ipoalerts.url=https://api.ipoalerts.in
ipoalerts.api.key=${IPOALERTS_API_KEY}

# JWT
jwt.secret.key=${JWT_SECRET_KEY}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


# Admin
mail.admin=${ADMIN_MAIL}

# spring.jpa.open-in-view=false